### ISSUE TITLE
crashing on single assest vaults (badger)

### ISSUE THREAD

**Issue by mitche50** [Badger-Finance/v2-ui#2413] opened 2022-10-04 20:31 UTC
Reported on: 2022-10-04T20:22:37.508000+00:00
Bug Description:
Multiple users experiencing crashes when accessing the Badger single-asset vault in the main app and unable to withdraw: https://app.badger.com

Attachments:
content_type: image/png
filename: unknown.png
height: 866
id: 1026952507479576626
proxy_url: https://media.discordapp.net/attachments/863051269337907210/1026952507479576626/unknown.png
size: 106248
url: https://cdn.discordapp.com/attachments/863051269337907210/1026952507479576626/unknown.png
width: 1060

**Comment by mrbasado** [comment] 2022-10-07 15:41
this should be a duplicate of the digg vault ticket #2355 . might happen for all single assest vaults

**Closed** 2022-10-17 17:37 UTC
Labels: bug
